### ISSUE TITLE
Make frontmatter configurable

### ISSUE THREAD

**Issue by B4rc1** [epwalsh/obsidian.nvim#34]
### 🚀 The feature, motivation and pitch

The current frontmatter generates three attributes:
- `id`, `aliases` and `tags`

I would like it to not generate the `id` and `aliases` attribute as I see no use for the `id` attribute and dislike that the `aliases` property pollutes my Quickswitcher results in Obsidian, every file shows up twice, once with alias, once with filepath. (this is not solved by disabling aliases or filepaths in the quickswitcher because for some Notes I want aliases as their filename is something completely different)

My solution would be to add a field to setup that lets the user define a function, taking the `filepath` and `note title` as arguments and return a lua table with the frontmatter attributes like so:

```lua
require("obsidian").setup({
  -- [...] rest of config
  frontmatter_func = function (filepath, note_title)
    return {
      id = "my_custom_id-" .. filepath,
      aliases = { note_title, "my_custom_alias"  },
      tags = { "custom_tag1", "custom_tag2" },
      my_custom_attribute = "value",
    }
  end
})
```

this should result in the following frontmatter:
```yaml
id: "my_custom_id-<filepath>"
aliases: 
  - <note_title>
  - my_custom_alias
tags: [ "custom_tag1", "custom_tag2" ]
my_custom_attribute: "value"
```
note however that in YAML this is equivalent to:
```yaml
id: "my_custom_id-<filepath>"
aliases: 
  - <note_title>
  - my_custom_alias
tags: 
  - "custom_tag1" 
  - "custom_tag2" 
my_custom_attribute: "value"
```
which is probably easier to implement because no special case needs to be made for the tags attributes to generate an array in the `[ <tag1> <tag2>]` format.

so for my usecase of not generating `id` and `alias` I would configure this:
```lua
require("obsidian").setup({
  -- [...] rest of config
  frontmatter_func = function (filepath, note_title)
    return {
      aliases = {},
    }
  end
})
```

and this should generate:
```yaml
aliases: []
```

### Alternatives

Have a boolean flag for which attribute to generate like so:
```lua
require("obsidian").setup({
  -- [...] rest of config
  frontmatter = {
    id = false,
    aliases = false,
    tags = true,
  };
})
```
this is a pretty crappy solution as it does not allow custom values for these attributes and no addition of custom attributes.

This would non the less solve my problem.
